name: Upload Image to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker buildx build --platform linux/arm/v7 --push -t jaimex8/docker-chromium-armhf .

      - name: Docker Logout
        run: docker logout
